### PR TITLE
fix(cat-gateway): Fix Chain Indexer metrics channel

### LINKED ISSUE #3162: Chain indexer metrics inconsistency
### Summary

Chain indexer metrics could show an inconsistent view of our system state. Its more visual on the indexer_current_immutable_tip_slot`, when its totally misaligned with the actual indexed immutable state.

### Description

`broadcast::Receiver<event::ChainIndexerEvent>` is used to get a latest state of the indexing process and correspondingly update the chain indexer metrics.
But `broadcast::Receiver<event::ChainIndexerEvent>` could (and that's what actually happening) skip some events (look at `broadcast::error::RecvError::Lagged`), which obviously leads to inconsistent view of the metrics.

### Solution

Get rid of the `event_channel` at all and update corresponding metrics directly in that places where events are dispatched right now

### PR DESCRIPTION
**Pull request by apskhem**
# Description

- Removed the broadcast channel completely from `SyncTask`
- Dispatch metrics value updater directly

## Related Issue(s)

Closes #3162 

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

File: catalyst-gateway/bin/src/cardano/mod.rs [hunk 1]
```diff
@@ -312,7 +301,7 @@ fn sync_subchain(
                     }
 
                     if chain_update.tip && !set_follower_live_first_reached_tip() {
-                        let _ = event_sender.send(event::ChainIndexerEvent::SyncLiveChainCompleted);
+                        metrics_updater::reached_tip(true, true);
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/cardano/mod.rs:304]: no no, we should update only for live tip, but this seems updating `immutable` metric

**Review by stevenj — COMMENTED** [review]
LGTM.  But can i ask for one more change?
Please update `.github/CODEOWNERS` and add josh to the path `catalyst-gateway/bin/src/metrics`

That way SRE will need to approve whenever we modify metrics, so we won't get a situation where metrics names change and SRE were not forewarned.

**Comment by apskhem** [comment]
> Can we also ensure the there are no metrics registered anywhere but under this path?

I think we can ensure that by simply checking the import from `prometheus::`. Right now, I can ensure that all the metrics are registered under this `metrics` module.

**Review by Mr-Leshiy — APPROVED** [review]
LGTM
