### PR TITLE
fix(wallet-tester): missing configurable aux hash and network ID

### LINKED ISSUE #499: [Bug]: wallet tester does not include auxiliary_data_hash and network_id in the transaction body cbor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Run wallet tester
2. Connect your wallet
3. Select `Sign transaction` from Wallet actions
4. Enter the following data into the form:

Transaction inputs:
UTXO Hex #1:
```
828258204c1fbc5433ec764164945d736a09dc087d59ff30e64d26d462ff8570cd4be9a70082583900c035332d2dcba35744e880729198459e32c50eb3e179b1fa2247348c80b846ad416f120db94c1a401992950b11b9bc7d65dbb3424c0f8de41b00000002540be400
```

Transaction outputs

| Address #1 | Amount #1 |
| ----------   | ----------  |
|addr_test1vzpwq95z3xyum8vqndgdd9mdnmafh3djcxnc6jemlgdmswcve6tkw   |   1000000|

Auxiliary Metadata | Transaction Metadata
Text:
| Label #1 | Metadatum #1 |
| ----------   | ----------  |
|1   |   Test|

5. Click `Build` button to get the unsigned transaction bytes
6. Inspect the transaction cbor at cbor.me and inspect if key 7 (auxiliary_data_hash) and key 15 (network_id) are included in the transaction body cbor.
7. Actual result (cbor): 
```
84A300818258204C1FBC5433EC764164945D736A09DC087D59FF30E64D26D462FF8570CD4BE9A700018282581D6082E016828989CD9D809B50D6976D9EFA9BC5B2C1A78D4B3BFA1BB83B1A000F424082583900C035332D2DCBA35744E880729198459E32C50EB3E179B1FA2247348C80B846AD416F120DB94C1A401992950B11B9BC7D65DBB3424C0F8DE41B0000000253FA156B021A00028C55A0F5A1016454657374
```
8. Actual result: Keys 7 & 15 missing
Screenshot 2024-05-16 at 14 33 33

### Expected Behavior

The transaction body contains the 7 & 15 keys for auxiliary_data_hash and network_id as per [documentation](https://input-output-hk.github.io/catalyst-voices/catalyst-standards/draft-cips/x509-rbac-signing-with-cip30/images/cardano-transaction.svg)

### Project

Frontend

### What operating system are you seeing the problem on?

Other

### What browsers are you seeing the problem on?

Not Applicable

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by apskhem**
# Description

Fixed missing configurable aux hash and network ID. Additionally remove polluted attributes from `cardano` object.

## Related Issue(s)

Closes #499 

## Description of Changes

* Fixed missing aux hash when build a transaction
* Added configurable network ID
* Fixed polluted attributes from the `cardano` object

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

**Review by stevenj — APPROVED** [review]
LGTM

File: utilities/wallet-tester/src/common/helpers/buildUnsignedTx.ts [hunk 1]
```diff
@@ -221,7 +218,15 @@ export default async function buildUnsignedTx(
   }
 
   // build a full transaction, passing in empty witness set
-  const unsignedTx = Transaction.new(txBuilder.build(), TransactionWitnessSet.new(), auxMetadata);
+  const txBody = txBuilder.build();
+  
+  // #15 add network id
+  if (builder.networkId && [0, 1].includes(Number(builder.networkId))) {
+    const networkId = Number(builder.networkId) === 0 ? NetworkId.testnet() : NetworkId.mainnet()
+    txBody.set_network_id(networkId);
```
Comment (dtscalac) [inline utilities/wallet-tester/src/common/helpers/buildUnsignedTx.ts:226]: I've tested this fix and when I included the network ID in the form then it was correctly set on the trasaction body. However the fee calculated for the transaction didn't get higher compared to a transaction that doesn't include the network_id. I think calling `txBody.set_network_id(networkId);` after `const txBody = txBuilder.build();` causes the fee to not include the network_id bytes, thus the calculated fee is not enough to cover for the transaction.
