### PR TITLE
fix(cat-gateway): Migrate EventDB from `bb8` to `deadpool`

### LINKED ISSUE #3428: migrate to `deadpool` connection pool manager
### Summary

Port the changes done by these PRs https://github.com/input-output-hk/catalyst-voices/pull/3290 and https://github.com/input-output-hk/catalyst-voices/pull/3341 to the `f15/cat-gateway` branch.

### Description

- Dont just cherry-pick the commits, the changes are simple, just make a corresponding and analogous changes for the `f15/cat-gateway` branch.

### PR DESCRIPTION
**Pull request by apskhem**
# Description

- Applied changes from these PRs https://github.com/input-output-hk/catalyst-voices/pull/3290 and https://github.com/input-output-hk/catalyst-voices/pull/3341 to the F15 release

## Related Issue(s)

Closes #3428

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

File: catalyst-gateway/bin/src/service/common/responses/mod.rs [hunk 1]
```diff
@@ -149,9 +149,7 @@ impl<T> WithErrorResponses<T> {
     /// Returns a Server Error or a Service Unavailable response.
     pub(crate) fn handle_error(err: &anyhow::Error) -> Self {
         match err {
-            err if err.is::<bb8::RunError<tokio_postgres::Error>>()
-                || err.is::<EventDBConnectionError>() =>
-            {
+            err if err.is::<EventDBConnectionError>() || err.is::<EventDBConnectionError>() => {
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/common/responses/mod.rs:152]: duplicate
```suggestion
            err if err.is::<EventDBConnectionError>() => {
```

**Review by Mr-Leshiy — CHANGES_REQUESTED** [review]

**Review by Mr-Leshiy — APPROVED** [review]
LGTM
