### PR TITLE
fix(cat-gateway): Use persistent state in volatile asset calculation

### LINKED ISSUE #2111: Cardano `assets` endpoint fix volatile data collection
### Summary

Need to fix how the volatile data for the cardano `assets` endpoint is being collected. It should be based on what data originally is collected from the persistent state, so it should be an extension of the persistent assets data rather than standalone calculations from the volatile db part.

### Description

Modify the cardano assets endpoint based on this branch https://github.com/input-output-hk/catalyst-voices/pull/2109

### PR DESCRIPTION
**Pull request by saibatizoku**
# Description

Extends the persistent state with volatile data for staked asset calculation.

## Related Issue(s)

Closes #2111 

## Please confirm the following checks

* [ ] My code follows the style guidelines of this project
* [ ] I have performed a self-review of my code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation
* [ ] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

File: catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs [hunk 1]
```diff
@@ -132,24 +136,53 @@ struct TxoInfo {
     spent_slot_no: Option<Slot>,
 }
 
+/// Calculate TXO State
+async fn _calculate_address_txo_data(
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs:140]: seems this is redundant and unused

**Review by Mr-Leshiy — APPROVED** [review]
LGTM
