### PR TITLE
fix: Missing `Content-Type` header in responses issue,

### LINKED ISSUE #434: [Bug]: Api 400 response content missing string type
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The open api linter is giving a warning about the 400 response missing some specification (see logs). This might be related with the failures we see for the 400 response with schemathesis tests.
To reproduce run `+test-lint-openapi` from `catalyst-voices/catalyst-gateway/tests`

### Expected Behavior

_No response_

### Project

Backend

### What operating system are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Not Applicable

### Relevant log output

warning  owasp:api4:2019-string-limit                     Schema of type string must specify maxLength, enum, or const.           paths./api/cardano/staked_ada/{stake_address}.get.responses[400].content['text/plain; charset=utf-8'].schema
       +lint-openapi *failed* |  1:12314      warning  owasp:api4:2019-string-restricted                Schema of type string must specify a format, pattern, enum, or const.   paths./api/cardano/staked_ada/{stake_address}.get.responses[400].content['text/plain; charset=utf-8'].schema

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
# Description

Fixed an issue with the missed `Content-Type` header for responses.
Enabled disabled lints of schematises.

## Related Issue(s)

Closes #434  #330  #457

## Description of Changes

- Fixed missing `Content-Type` header issue.
- Fixed 400 BadRequest response schema from plain text to Json.
- Removed `poem-extensions` dep, refactored all endpoints with the new approach.
- Removed unused test endpoints (seems we have already enough references to play with).
- Bumped version of the poem to the latest one

### CODE REVIEW

File: catalyst-gateway/tests/Earthfile
Comment (kukkok3) [inline catalyst-gateway/tests/Earthfile:1]: I think we can remove this comment now?

`# enable this linting after this issue will be solved`

**Review by kukkok3 — APPROVED** [review]
LGTM

File: catalyst-gateway/bin/src/service/api/legacy/v1/fragments_post.rs [hunk 1]
```diff
@@ -1,39 +1,23 @@
...
+pub(crate) enum AllResponses {
+    /// Fragments processing summary
+    #[oai(status = 200)]
+    Ok(Json<FragmentsProcessingSummary>),
+}
 
 /// # GET /fragments
 ///
 /// Process a fragments batch.
-///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/legacy/v1/fragments_post.rs:28]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/legacy/v1/account_votes_get.rs [hunk 2]
```diff
@@ -3,47 +3,30 @@
...
+    Ok(Json<Vec<AccountVote>>),
+}
 
 /// GET /v1/votes/plans/account-votes/:account_id
 ///
 /// Get votes for an `account_id` endpoint.
 ///
 /// For each active vote plan, this endpoint returns an array
 /// with the proposal index number that the account voted for.
-///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/legacy/v1/account_votes_get.rs:35]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/legacy/v0/plans_get.rs [hunk 3]
```diff
@@ -3,43 +3,22 @@
...
+pub(crate) enum AllResponses {
+    /// JSON array with the list of vote plans with their respective data.
+    #[oai(status = 200)]
+    Ok(Json<Vec<VotePlan>>),
+}
 
 /// GET /v0/vote/active/plans
 ///
 /// Get all active vote plans endpoint.
-///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/legacy/v0/plans_get.rs:32]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/legacy/v0/message_post.rs [hunk 4]
```diff
@@ -1,42 +1,27 @@
...
+    #[oai(status = 200)]
+    Ok(Json<FragmentsProcessingSummary>),
+}
 
 /// # POST /message
 ///
 /// Message post endpoint.
 ///
 /// When successful, returns a summary of fragments accepted and rejected.
-///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/legacy/v0/message_post.rs:28]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/health/started_get.rs [hunk 5]
```diff
@@ -33,16 +32,7 @@ pub(crate) type AllResponses = response! {
 /// into memory or processed in some way before the API can return valid
 /// responses.  In that scenario this endpoint would return 503 until that
 /// startup processing was fully completed.
-///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/health/started_get.rs:36]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/health/ready_get.rs [hunk 6]
```diff
@@ -43,24 +39,16 @@ pub(crate) type AllResponses = response! {
 /// and is not able to properly service requests while it is occurring.
 /// This would let the load balancer shift traffic to other instances of this
 /// service that are ready.
-///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/health/ready_get.rs:46]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/health/mod.rs [hunk 7]
```diff
@@ -66,13 +52,6 @@ impl HealthApi {
     ///
     /// *This endpoint is for internal use of the service deployment infrastructure.
     /// It may not be exposed publicly. Refer to []*
-    ///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/health/mod.rs:69]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/health/mod.rs [hunk 8]
```diff
@@ -46,13 +39,6 @@ impl HealthApi {
     ///
     /// *This endpoint is for internal use of the service deployment infrastructure.
     /// It may not be exposed publicly.*
-    ///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/health/mod.rs:49]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/health/mod.rs [hunk 9]
```diff
@@ -25,13 +25,6 @@ impl HealthApi {
...
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/health/mod.rs:28]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/health/live_get.rs [hunk 10]
```diff
@@ -26,24 +24,7 @@ pub(crate) type AllResponses = response! {
 ///
 /// In this service, liveness is assumed unless there are multiple panics generated
 /// by an endpoint in a short window.
-///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/health/live_get.rs:29]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/cardano/mod.rs [hunk 11]
```diff
@@ -149,13 +125,6 @@ impl CardanoApi {
     ///
     /// This endpoint returns the closest cardano slot info to the provided
     /// date-time.
-    ///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/cardano/mod.rs:152]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/cardano/mod.rs [hunk 12]
```diff
@@ -119,14 +103,6 @@ impl CardanoApi {
     /// Get Cardano follower's sync state.
     ///
     /// This endpoint returns the current cardano follower's sync state info.
-    ///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/cardano/mod.rs:122]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/cardano/mod.rs [hunk 13]
```diff
@@ -80,14 +72,6 @@ impl CardanoApi {
     ///
     /// This endpoint returns the registration info followed by the [CIP-36](https://cips.cardano.org/cip/CIP-36/) to the
     /// corresponded user's stake address.
-    ///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/cardano/mod.rs:83]: Why remove documentation?

File: catalyst-gateway/bin/src/service/api/cardano/mod.rs [hunk 14]
```diff
@@ -40,14 +40,6 @@ impl CardanoApi {
     ///
     /// This endpoint returns the total Cardano's staked ada amount to the corresponded
     /// user's stake address.
-    ///
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/cardano/mod.rs:43]: Why remove documentation?

File: catalyst-gateway/Cargo.lock
Comment (stevenj) [inline catalyst-gateway/Cargo.lock:1]: We don't want cargo.lock in the repo.

**Review by stevenj — CHANGES_REQUESTED** [review]
See comments.
Also, this PR needs to be updated from `main` branch and all conflicts resolved.

**Comment by Mr-Leshiy** [comment]
attaching diff file of the OpenAPI docs schema
[docs.diff.json](https://github.com/input-output-hk/catalyst-voices/files/15306226/docs.diff.json)

File: catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart [hunk 15]
```diff
@@ -1,22 +1,6 @@
 import 'package:json_annotation/json_annotation.dart';
```
[the remark this answers is not in the document]
Comment (Mr-Leshiy) [reply catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart:1]: We can do that way, but on one of our tech discussion as a remember we have decided to make them as a part of the repo and just make a check in our CI.

File: catalyst-gateway/bin/src/service/api/legacy/v1/fragments_post.rs (hunk 1 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/legacy/v1/fragments_post.rs:28]: All such documentation appears as a part of Responses definition, like that:
```
/// Endpoint responses.
#[derive(ApiResponse)]
pub(crate) enum Responses {
    /// Service is OK and can keep running.
    #[oai(status = 204)]
    NoContent,
}
```
Leaving such documentation at this place would be a duplicance and a maintenance issue.
Because after we will change a `Responses` type it is also needed to update docs at this place, which could be easily messed up.

File: catalyst-gateway/bin/src/service/api/cardano/mod.rs (hunk 14 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/cardano/mod.rs:43]: same

File: catalyst-gateway/bin/src/service/api/cardano/mod.rs (hunk 13 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/cardano/mod.rs:83]: same

File: catalyst-gateway/bin/src/service/api/cardano/mod.rs (hunk 12 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/cardano/mod.rs:122]: same

File: catalyst-gateway/bin/src/service/api/cardano/mod.rs (hunk 11 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/cardano/mod.rs:152]: same

File: catalyst-gateway/bin/src/service/api/health/live_get.rs (hunk 10 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/health/live_get.rs:29]: same

File: catalyst-gateway/bin/src/service/api/health/mod.rs (hunk 9 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/health/mod.rs:28]: same

File: catalyst-gateway/bin/src/service/api/health/mod.rs (hunk 8 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/health/mod.rs:49]: same

File: catalyst-gateway/bin/src/service/api/health/mod.rs (hunk 7 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/health/mod.rs:69]: same

File: catalyst-gateway/bin/src/service/api/health/ready_get.rs (hunk 6 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/health/ready_get.rs:46]: same

File: catalyst-gateway/bin/src/service/api/health/started_get.rs (hunk 5 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/health/started_get.rs:36]: same

File: catalyst-gateway/bin/src/service/api/legacy/v0/message_post.rs (hunk 4 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/legacy/v0/message_post.rs:28]: same

File: catalyst-gateway/bin/src/service/api/legacy/v0/plans_get.rs (hunk 3 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/legacy/v0/plans_get.rs:32]: same

File: catalyst-gateway/bin/src/service/api/legacy/v1/account_votes_get.rs (hunk 2 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/api/legacy/v1/account_votes_get.rs:35]: same

File: catalyst-gateway/tests/schemathesis-docker-compose.yml [hunk 16]
```diff
@@ -34,8 +34,8 @@ services:
       - DATA_REFRESH_TICK=5
       - CHECK_CONFIG_TICK=5
       - MACHINE_ID="UID"
-    container_name: cat-gateway
-    network_mode: "host"
+    ports:
```
[the remark this answers is not in the document]
Comment (Mr-Leshiy) [reply catalyst-gateway/tests/schemathesis-docker-compose.yml:37]: Such properties like `container_name` and `network_mode` just not used and not necessary, that's why I removed them.

File: catalyst-gateway/tests/api_tests/docker-compose.yml [hunk 17]
```diff
@@ -34,7 +34,6 @@ services:
       - DATA_REFRESH_TICK=5
       - CHECK_CONFIG_TICK=5
       - MACHINE_ID="UID"
-    hostname: gateway
```
[the remark this answers is not in the document]
Comment (Mr-Leshiy) [reply catalyst-gateway/tests/api_tests/docker-compose.yml:37]: same, we it just not needed for this container used in tests

File: catalyst-gateway/tests/schemathesis-docker-compose.yml (hunk 16 above)
[the remark this answers is not in the document]
Comment (stevenj) [reply catalyst-gateway/tests/schemathesis-docker-compose.yml:37]: Why did we need to add ports?
Did it not work before?

File: catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs [hunk 18]
```diff
@@ -13,25 +9,26 @@ use crate::{
...
-    200: OK<Json<StakeInfo>>,
-    400: ApiValidationError,
-    404: NotFound,
-    500: ServerError,
-    503: ServiceUnavailable,
-};
+/// Endpoint responses.
+#[derive(ApiResponse)]
+pub(crate) enum Responses {
+    /// Returns the staked ada amount.
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs:22]:
```suggestion
    /// The amount of ADA staked by the queried stake address, as at the indicated slot.
```

File: catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs [hunk 19]
```diff
@@ -13,25 +9,26 @@ use crate::{
...
+    #[oai(status = 200)]
+    Ok(Json<StakeInfo>),
+    /// Nothing found for the provided stake address and provided slot number.
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs:25]:
```suggestion
    /// The queried stake address was not found at the requested slot number.
```

File: catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs [hunk 20]
```diff
@@ -1,32 +1,29 @@
...
-    200: OK<Json<SyncState>>,
-    400: ApiValidationError,
-    404: NotFound,
-    500: ServerError,
-    503: ServiceUnavailable,
-};
+/// Endpoint responses.
+#[derive(ApiResponse)]
+pub(crate) enum Responses {
+    /// Returns the sync state.
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs:17]:
```suggestion
    /// The synchronisation state of the blockchain with the catalyst gateway service.
```

File: catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs [hunk 21]
```diff
@@ -1,32 +1,29 @@
...
+    #[oai(status = 200)]
+    Ok(Json<SyncState>),
+    /// Cardano chain follower was not syncing for the provided network.
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs:20]:
```suggestion
    /// The network is unknown. Catalayst gateway is not syncing the queried network.
```

File: catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart (hunk 15 above)
[the remark this answers is not in the document]
Comment (stevenj) [reply catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart:1]: Ok, its fine as is.

**Review by stevenj — CHANGES_REQUESTED** [review]
See comments.
We can not loses the documentation about the distinction of 503 in the health endpoints, and i have suggested better wording for a bunch of document comments which end up in the API document.

File: catalyst-gateway/bin/src/service/api/health/ready_get.rs [hunk 22]
```diff
@@ -17,6 +17,10 @@ pub(crate) enum Responses {
     /// Service is Started and can serve requests.
     #[oai(status = 204)]
     NoContent,
+    /// Service is not ready, do not send other requests.
+    #[oai(status = 503)]
+    #[allow(dead_code)]
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/health/ready_get.rs:22]: Not sure why this is dead code, it is being used in the endpoint?

File: catalyst-gateway/bin/src/service/api/health/started_get.rs [hunk 23]
```diff
@@ -10,6 +10,10 @@ pub(crate) enum Responses {
     /// Service is Started and can serve requests.
     #[oai(status = 204)]
     NoContent,
+    /// Service is not ready, do not send other requests.
+    #[oai(status = 503)]
+    #[allow(dead_code)]
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/health/started_get.rs:15]: Not sure why this is "dead_code"?

This endpoint should have a global state variable that defaults to false.
When cat-gateway is finished "starting", ie it has started all its internal services, and is ready to serve requests, it should get set to true (by a function call).
Then endpoint then should check,  if started, return NoContent else return ServiceUnavailable

File: catalyst-gateway/bin/src/service/api/health/live_get.rs [hunk 24]
```diff
@@ -10,6 +10,10 @@ pub(crate) enum Responses {
     /// Service is OK and can keep running.
     #[oai(status = 204)]
     NoContent,
+    /// Service is possibly not running reliably.
+    #[oai(status = 503)]
+    #[allow(dead_code)]
+    ServiceUnavailable,
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/api/health/live_get.rs:16]: Ok, the logic here is also needs expansion.
Similar to "started" we should have a global state variable called "ready" which defaults to true. 
A function (which can be marked "dead_code" for now, until its used, can set that variable to false.
The endpoint then return NoContent if its true, and ServiceUnavailable otherwise.

**Review by stevenj — CHANGES_REQUESTED** [review]
See comments on health endpoints.
I know it's not part of this ticket, but these changes are small, and i think we should get the logic right here, so that the ServiceUnavailable logic is in place properly.

Put the call to set "started" true after everything has been set up and is running, and we are ready to process requests in the main service init code.

The "Ready" endpoint should already not need dead_code on its ServiceUnavailable response.

Otherwise, I like this approach.

File: catalyst-gateway/tests/schemathesis-docker-compose.yml (hunk 16 above)
[the remark this answers is not in the document]
Comment (Mr-Leshiy) [reply catalyst-gateway/tests/schemathesis-docker-compose.yml:37]: Yes, it was disabled, after I have enabled it didn't work

**Review by stevenj — DISMISSED** [review]
Thanks for all the cleanups.
LGTM.

**Review by minikin — APPROVED** [review]
