### PR TITLE
fix(cat-gateway): Signed Document Index endpoint  pagination bug fix

### LINKED ISSUE #2075: POST `document/index` incorrect docs count
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When sending empty filter object and `limit=100` docs objects count it a  33 but `remaining` says it still has 8 left.
When asking for `page=1` `docs` is empty

Request
```bash
curl -s --request POST \
  --url https://gateway.dev.projectcatalyst.io/api/v1/document/index \
  --header 'Accept: application/json; charset=utf-8' \
  --header 'Content-Type: application/json; charset=utf-8' \
  --data '{}' | jq
```

Response
```json
{
  "docs": [
    {
      "id": "067dadad-e3d2-7b6f-8000-4c0784888ccf",
      "ver": [
        {
          "template": {
            "id": "0194d492-1daa-75b5-b4a4-5cf331cd8d1a"
          },
          "type": "7808d2ba-d511-40af-84e8-c0d1625fdfdc",
          "ver": "067dadad-fe0f-7ebd-8000-517ea478e1de"
        },
        {
          "template": {
            "id": "0194d492-1daa-75b5-b4a4-5cf331cd8d1a"
          },
          "type": "7808d2ba-d511-40af-84e8-c0d1625fdfdc",
          "ver": "067dadad-e3d2-7b6f-8000-4c0784888ccf"
        }
      ]
    },
    ...
  ],
  "page": {
    "limit": 100,
    "page": 0,
    "remaining": 8
  }
}
``` 

### Expected Behavior

count of top **level** docs items matching `limit` and `remaining` is reflected when asking for subsequent pages. 

### Project

Backend

### What operating system are you seeing the problem on?

macOS

### What browsers are you seeing the problem on?

Not Applicable

### Relevant log output

```sh

```

### Anything else?

Slack thread ([link](https://input-output-rnd.slack.com/archives/C04H3D237DF/p1742568531711089)) 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by saibatizoku**
# Description

Fixes bug where signed document index enpoint pagination returned incorrect number of remaining documents.

## Related Issue(s)

Closes #2075 .

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

File: catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs [hunk 1]
```diff
@@ -103,14 +98,25 @@ pub(crate) async fn endpoint(
...
+) -> anyhow::Result<(Vec<IndexedDocumentDocumented>, u32)> {
     let docs_stream = SignedDocBody::retrieve(conditions, query_limits).await?;
     let indexed_docs = DashMap::new();
 
+    let mut total_fetched_doc_count: u32 = 0;
     docs_stream
         .try_for_each(|doc: SignedDocBody| {
             let id = *doc.id();
             indexed_docs.entry(id).or_insert_with(Vec::new).push(doc);
+            match total_fetched_doc_count.checked_add(1) {
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs:110]: What do you think of changing this `try_for_each` to 
```rust
let (indexed_docs, total_fetched_doc_count) = docs_stream .try_fold(
(HashMap::new(), 0),
 |(mut indexed_docs, mut total_fetched_doc_count), doc| 
 async move {
       let id = *doc.id();
       indexed_docs.entry(id).or_insert_with(Vec::new).push(doc);
       total_fetched_doc_count.checked_add(1).ok_or(anyhow::anyhow!(
                        "Fetched Signed Documents overflow"
                    ))?;
  Ok(indexed_docs, total_fetched_doc_count)     
 }
 ).await?;
 ```
 If I am not mistaken it could allow to avoid using of `DashMap` and use simple `HashMap`

**Review by Mr-Leshiy — CHANGES_REQUESTED** [review]

File: catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs (hunk 1 above)
Comment (saibatizoku) [reply catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs]: Yup, this works.

**Review by Mr-Leshiy — APPROVED** [review]
LGTM
