### PR TITLE
fix: redirecting after keychain is deleted

### LINKED ISSUE #1090: [Bug]: MVE2 fix: redirect after remove keychain
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

GIVEN a user wants to remove keychain from my account page
WHEN confirm remove keychain
THEN user see "keychain removed" confirmation
AND WHEN user click "close"
THEN user stays in my account
AND IF user clicks "remove keychain" again
THEN user infinite loop

Image

### Expected Behavior

After confirming keychain removal, then...
- Redirect user to discovery page
- Put app into no keychain / visitor state

### Project

Frontend

### What operating system are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by damian-molinski**
# Description

Redirects to discovery page after keychain is deleted + update strings for delete confirmation dialog.

Note. i was not able to implement auto redirect via Router `refreshListenable` for some strange reason. Router state was updating but page did not change at all

## Related Issue(s)

Fixes #1090

### CODE REVIEW

File: catalyst_voices/apps/voices/lib/routes/routing/router_refresh_stream.dart [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import 'dart:async';
+
+import 'package:flutter/foundation.dart';
+
+final class RouterRefreshStream extends ChangeNotifier {
```
Comment (dtscalac) [inline catalyst_voices/apps/voices/lib/routes/routing/router_refresh_stream.dart:5]: Is this class needed?

Comment (damian-molinski) [reply catalyst_voices/apps/voices/lib/routes/routing/router_refresh_stream.dart:5]: Yeah, not really. Leftover from trying to implement `refreshListenable`

**Review by dtscalac — APPROVED** [review]
LGTM
