### PR TITLE
fix(cat-voices): allow duplicate seed phrase words

### LINKED ISSUE #973: [Bug]: Allow duplicated words in a seed phrase
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When entering the seed words the UI doesn't allow to enter duplicated words:

Screenshot 2024-10-08 at 09 20 34

### Expected Behavior

Seed phrase UI allows to enter duplicated words, example seed phrase:

[catalyst_seed_phrase(1).txt](https://github.com/user-attachments/files/17289571/catalyst_seed_phrase.1.txt)

From BIP-39:

```
The BIP39 standard doesn't allow for any word to be repeated more than two times in a seed phrase
```

### Project

Frontend

### What operating system are you seeing the problem on?

Other

### What browsers are you seeing the problem on?

Not Applicable

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by damian-molinski**
# Description

Allows to correctly select seed phrase words when duplicates are present

## Related Issue(s)

Fixes #973 

## Description of Changes

Introduces `SeedPhraseWord` to keep track of which word is which.

## Related Pull Requests

Relates to #978 and should be updated after merging it.

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

File: catalyst_voices/packages/catalyst_voices_models/lib/src/seed_phrase.dart [hunk 1]
```diff
@@ -6,10 +6,36 @@ import 'dart:typed_data';
...
+///
+/// This is useful because seed phrase may have duplicate words. With this
+/// structure we can distinguish which word is which.
+final class SeedPhraseWord extends Equatable
+    implements Comparable<SeedPhraseWord> {
+  /// Word value.
+  final String data;
+
+  /// Number of this word in [SeedPhrase].
+  final int nr;
```
Comment (dtscalac) [inline catalyst_voices/packages/catalyst_voices_models/lib/src/seed_phrase.dart:25]: Call it index? Programmers use indexes, kinda seems more familiar than a number, what do you think?

Comment (damian-molinski) [reply catalyst_voices/packages/catalyst_voices_models/lib/src/seed_phrase.dart:25]: its intentionally `nr` and not `index`. 
My reasoning was that we do stuff like `shuffling`, after that it won't make sense to have `SeedPhraseWord` with `index:0` in list at index `9` but having `SeedPhraseWord` nr. `1` at index `9` makes little more sense.

**Review by digitalheartxs — APPROVED** [review]

**Review by dtscalac — APPROVED** [review]

**Review by digitalheartxs — APPROVED** [review]

**Review by dtscalac — APPROVED** [review]
