### PR TITLE
fix(cat-gateway): Get static doc template

### LINKED ISSUE #1732: 🛠️ [TASK] : Implement static doc template for in `GET` for sign document
### Summary

Implement static doc template for `GET` sign document

### Description

Retrieve static document template if requested for sign document `GET`

- The static document need to be signed
- There should be 12 categories which each link to a unique proposal template and also comment template
- Each ID and version should be the same for this iteration
- There is no predefined value for ID, so it can be explicitly generated
- Doc type is already defined in https://input-output-hk.github.io/catalyst-libs/architecture/08_concepts/signed_doc/types/

### PR DESCRIPTION
**Pull request by bkioshn**
# Description

Implement static doc template for `GET` sign document

## Related Issue(s)

Closes #1732

## Description of Changes

- Sign doc `GET` now look for static template according to version and ID
- Create `SignedDocTemplate`
- Create JSON utils

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [ ] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

**Review by stanislav-tkach — DISMISSED** [review]

**Comment by stanislav-tkach** [comment]
I'm not sure it is worth the effort, but maybe we want to add tests that load and deserialize all these JSON files (such as `default/frontend.json`, `default/frontend_ip.json`, etc.)?.. Because currently we print an error in the log and return an empty object, so tests can catch invalid files earlier.

File: catalyst-gateway/bin/src/service/api/documents/templates/proposal.rs [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+/// Proposal document template type as UUID V4.
+const DOC_TYPE: &str = "0ce8ab38-9258-4fbc-a62e-7faa6e58318f";
+
+/// Proposal document template.
+pub(crate) static PROPOSAL: LazyLock<SignedDocTemplate> = LazyLock::new(|| {
+    SignedDocTemplate {
+        id: "0194b595-da01-73e8-91be-d22687faf577".to_owned(),
+        ver: "0194b597-eeb9-7d0b-9b92-8b306ba5816d".to_owned(),
+        doc_type: DOC_TYPE.to_owned(),
+        content: serialize_to_bytes(&load_json(include_str!(
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/documents/templates/proposal.rs:18]: I think you can just use `include_bytes!` [macro](https://doc.rust-lang.org/std/macro.include_bytes.html), without trying to build a json doc at this place. All the necessary validation in any case would be done during catalyst signed doc building process

File: catalyst-gateway/bin/src/service/api/documents/templates/mod.rs [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+mod proposal;
+
+use std::sync::LazyLock;
+
+use catalyst_signed_doc::{Builder, CatalystSignedDocument, Metadata};
+use minicbor::{Encode, Encoder};
+use proposal::PROPOSAL;
+
+/// A list of templates.
+pub(crate) static TEMPLATES: LazyLock<[CatalystSignedDocument; 1]> =
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/documents/templates/mod.rs:12]: Add a unit test with instantiating this `static TEMPLATES`

File: catalyst-gateway/bin/src/service/api/documents/templates/proposal.rs [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+use crate::service::utilities::json::{load_json, serialize_to_bytes};
+
+/// Proposal document template type as UUID V4.
+const DOC_TYPE: &str = "0ce8ab38-9258-4fbc-a62e-7faa6e58318f";
+
+/// Proposal document template.
+pub(crate) static PROPOSAL: LazyLock<SignedDocTemplate> = LazyLock::new(|| {
+    SignedDocTemplate {
+        id: "0194b595-da01-73e8-91be-d22687faf577".to_owned(),
+        ver: "0194b597-eeb9-7d0b-9b92-8b306ba5816d".to_owned(),
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/documents/templates/proposal.rs:16]: No no no, `id` and `ver` for the first version of the document should be the same

**Review by Mr-Leshiy — CHANGES_REQUESTED** [review]

File: catalyst-gateway/bin/src/service/api/documents/templates/mod.rs [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+}
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+
+    #[test]
+    fn templates() {
+        for tem in TEMPLATES.iter() {
+            assert!(tem.doc_id().is_valid());
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/documents/templates/mod.rs:84]:
```suggestion
```

File: catalyst-gateway/bin/src/service/api/documents/templates/mod.rs [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+            assert!(tem.doc_ver().is_valid());
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/documents/templates/mod.rs:85]:
```suggestion
```

File: catalyst-gateway/bin/src/service/api/documents/templates/mod.rs [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+            assert!(tem.doc_type().is_valid());
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/documents/templates/mod.rs:86]:
```suggestion
```

**Review by Mr-Leshiy — APPROVED** [review]
LGTM

File: catalyst-gateway/bin/src/service/utilities/json.rs [hunk 7]
```diff
@@ -0,0 +1,12 @@
+//! JSON related utilities.
+
+use serde_json::{json, Value};
+use tracing::error;
+
+/// Convert a JSON string to a JSON value.
+pub(crate) fn load_json(data: &str) -> Value {
+    serde_json::from_str(data).unwrap_or_else(|err| {
+        error!(id="load_json", error=?err, "Error parsing JSON");
+        json!({})
```
Comment (apskhem) [inline catalyst-gateway/bin/src/service/utilities/json.rs:10]: Instead of return an empty object, why don't you return `Value::Null`? So in this way, it can be easier to compare/check against the null value.

Comment (bkioshn) [reply catalyst-gateway/bin/src/service/utilities/json.rs:10]: From what I remember if there is an error, it should still need to pass the schema validation which is a type object.
