### PR TITLE
fix(cat-gateway): Fix rbac indexing

### LINKED ISSUE #1366: Fix issues with RBAC in cat-gateway
Fix RBAC indexing issues discovered inside cat-gateway in preparation for further work on RBAC.

### PR DESCRIPTION
**Pull request by stevenj**
# Description

Fixes RBAC indexing issues discovered inside cat-gateway.

## Related Issue(s)

Closes #1366, https://github.com/input-output-hk/catalyst-voices/issues/1759

## Description of Changes

Fix RBAC indexing so it works properly and has no boundary conditions.

## Breaking Changes

Nothing relies on it yet, so none.

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

File: catalyst-gateway/bin/src/db/types/mod.rs [hunk 1]
```diff
@@ -0,0 +1,15 @@
+//! Wrappers over commonly used types that can be stored to and load from a database.
+
+pub use slot::DbSlot;
```
Comment (bkioshn) [inline catalyst-gateway/bin/src/db/types/mod.rs:3]: Do we need this DbType 🤔

Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/types/mod.rs:4]: I can don't mind removing it if we decide so, but I think that the following types are confusing:
```rust
type PrimaryKey = (Vec<u8>, Vec<u8>, num_bigint::BigInt, i16, bool);
type PrimaryKey = (Vec<u8>, num_bigint::BigInt, i16, i16, Vec<u8>, Vec<u8>);
```
It isn't clear what these fields represent. Proper types can make reading such code easier and modifying it less error prone.

File: catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_invalid_registrations.rs [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+    /// A Catalyst ID.
+    pub catalyst_id: DbCatalystId,
+}
+
+/// Get invalid registrations by Catalyst ID query.
+#[allow(dead_code)]
+#[derive(DeserializeRow)]
+pub(crate) struct Query {
+    /// Registration transaction id.
+    pub transaction_id: Vec<u8>,
```
Comment (bkioshn) [inline catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_invalid_registrations.rs:34]:
```suggestion
    pub transaction_id: DbTransactionHash
```

File: catalyst-gateway/bin/src/db/index/schema/cql/catalyst_id_for_stake_addr.cql [hunk 3]
```diff
@@ -0,0 +1,13 @@
+-- Index of Catalyst ID For Stake Address. RBAC 509 registrations.
+CREATE TABLE IF NOT EXISTS catalyst_id_for_stake_addr (
+    -- Primary Key Data
+    stake_addr          blob,       -- 29 Byte Stake Address (CIP19)
+    slot_no             bigint,     -- Slot number when the key_was_registered. (u64)
+    txn                 smallint,   -- Index of the TX which holds the registration data. (i16)
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/schema/cql/catalyst_id_for_stake_addr.cql:6]: I think it makes sense to use `txn_idx` everywhere for clarity.

[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/schema/cql/catalyst_id_for_stake_addr.cql:6]: We decided to proceed with `txn_index` and `txn_id` everywhere for consistency and to avoid confusion with names such as `txn`, `txn_idx`, `txn_id`, etc.

File: catalyst-gateway/bin/Cargo.toml [hunk 4]
```diff
@@ -88,20 +88,21 @@ num-traits = "0.2.19"
 base64 = "0.22.1"
 dashmap = "6.1.0"
 x509-cert = "0.2.5"
-der-parser = "9.0.0"
 jsonschema = "0.26.1"
 bech32 = "0.11.0"
 const_format = "0.2.33"
 regex = "1.11.1"
+as-slice = "0.2.1"
+to_vec = "0.1.0"
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/Cargo.toml]: I have remove `as-slice` as well.

File: catalyst-gateway/bin/src/db/index/block/rbac509/insert_rbac509_invalid.rs [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+        )
+        .map_err(|error| anyhow::anyhow!("{error}\n--\n{QUERY}"))
+    }
+}
+
+impl Debug for Params {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        let prv_txn_id = match self.prv_txn_id {
+            MaybeUnset::Unset => "UNSET".to_owned(),
+            MaybeUnset::Set(v) => format!("{v:?}"),
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/db/index/block/rbac509/insert_rbac509_invalid.rs:88]: Are sure that it should be a `format!("{v:?}")` instead of `format!("{v}")`?

File: catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_invalid_registrations.rs [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+    pub problem_report: String,
+}
+
+impl Query {
+    /// Prepares a query.
+    pub(crate) async fn prepare(session: Arc<Session>) -> anyhow::Result<PreparedStatement> {
+        PreparedQueries::prepare(session, QUERY, Consistency::All, true)
+            .await
+            .inspect_err(
+                |e| error!(error=%e, "Failed to prepare get registrations by Catalyst ID query"),
```
Comment (bkioshn) [inline catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_invalid_registrations.rs:53]:
```suggestion
                |e| error!(error=%e, "Failed to prepare get invalid RBAC registrations by Catalyst ID query"),
```

File: catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_registrations.rs [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+    pub purpose: DbUuidV4,
+}
+
+impl Query {
+    /// Prepares a query.
+    pub(crate) async fn prepare(session: Arc<Session>) -> anyhow::Result<PreparedStatement> {
+        PreparedQueries::prepare(session, QUERY, Consistency::All, true)
+            .await
+            .inspect_err(
+                |e| error!(error=%e, "Failed to prepare get registrations by Catalyst ID query"),
```
Comment (bkioshn) [inline catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_registrations.rs:51]:
```suggestion
                |e| error!(error=%e, "Failed to prepare get RBAC registrations by Catalyst ID query"),
```

File: catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs [hunk 8]
```diff
@@ -93,15 +98,15 @@ struct TxoInfo {
     /// TXO value.
     value: num_bigint::BigInt,
     /// TXO transaction hash.
-    txn_hash: Vec<u8>,
+    txn_hash: TransactionHash,
```
Comment (bkioshn) [inline catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs:101]: txn_id

**Review by bkioshn — COMMENTED** [review]
Made some comment on typo but there are some more mismatch between comments and code. I think it is better to revisit it in other PR and check for consistency. Manually tested, existed some data in all table. Besides from the dependency tags, overall LGTM

**Comment by stanislav-tkach** [comment]
I will remove the draft status now, but I will do one more self-review at the morning.

File: catalyst-gateway/bin/src/db/index/block/txo/cql/insert_txo.cql [hunk 9]
```diff
@@ -1,16 +1,16 @@
 -- Create the TXO Record for a stake address,
 INSERT INTO txo_by_stake (
-    stake_address,
+    stake_hash,
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/block/txo/cql/insert_txo.cql:3]:
```suggestion
    stake_address,
```

File: catalyst-gateway/bin/src/db/index/block/txo/cql/insert_txo.cql [hunk 10]
```diff
@@ -1,16 +1,16 @@
...
-    txn,
+    txn_index,
     txo,
     address,
     value,
-    txn_hash
+    txn_id
 ) VALUES (
-    :stake_address,
+    :stake_hash,
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/block/txo/cql/insert_txo.cql:11]:
```suggestion
    :stake_address,
```

File: catalyst-gateway/bin/src/db/index/block/txo/cql/insert_txo_asset.cql [hunk 11]
```diff
@@ -1,17 +1,17 @@
...
     slot_no,
-    txn,
+    txn_index,
     txo,
     policy_id,
     asset_name,
     value
 ) VALUES (
-    :stake_address,
+    :stake_hash,
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/block/txo/cql/insert_txo_asset.cql:12]:
```suggestion
    :stake_address,
```

File: catalyst-gateway/bin/src/db/index/block/txo/insert_txo.rs [hunk 12]
```diff
@@ -20,35 +24,35 @@ const INSERT_TXO_QUERY: &str = include_str!("./cql/insert_txo.cql");
...
     /// Create a new record for this transaction.
     pub(crate) fn new(
-        stake_address: &[u8], slot_no: u64, txn: i16, txo: i16, address: &str, value: u64,
-        txn_hash: &[u8],
+        stake_hash: &[u8], slot_no: Slot, txn_index: TxnIndex, txo: TxnOutputOffset, address: &str,
+        value: u64, txn_hash: TransactionHash,
     ) -> Self {
         Self {
-            stake_address: stake_address.to_vec(),
+            stake_hash: stake_hash.to_vec(),
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/block/txo/insert_txo.rs:49]:
```suggestion
            stake_address: stake_address.to_vec(),
```

File: catalyst-gateway/bin/src/db/index/block/txo/insert_txo_asset.rs [hunk 13]
```diff
@@ -17,14 +21,14 @@ const INSERT_TXO_ASSET_QUERY: &str = include_str!("./cql/insert_txo_asset.cql");
 /// (Superset of data to support both Staked and Unstaked TXO records.)
 #[derive(SerializeRow, Debug)]
 pub(crate) struct Params {
-    /// Stake Address - Binary 28 bytes. 0 bytes = not staked.
-    stake_address: Vec<u8>,
+    /// Stake Address - Binary 29 bytes. 0 bytes = not staked.
+    stake_hash: Vec<u8>,
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/block/txo/insert_txo_asset.rs:25]:
```suggestion
    stake_address: Vec<u8>,
```

Never use 0 bytes, if it has no stake address, don't store it here.

File: catalyst-gateway/bin/src/db/index/queries/cql/get_assets_by_stake_address.cql [hunk 14]
```diff
@@ -1,10 +1,10 @@
...
-    txn,
+    txn_index,
     txo,
     slot_no,
     policy_id,
     asset_name,
     value
 FROM txo_assets_by_stake
-WHERE stake_address = :stake_address
+WHERE stake_hash = :stake_hash
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/queries/cql/get_assets_by_stake_address.cql:9]:
```suggestion
WHERE stake_address = :stake_address
```

File: catalyst-gateway/bin/src/db/index/queries/cql/get_catalyst_id_for_stake_hash.cql [hunk 15]
```diff
@@ -0,0 +1,8 @@
+SELECT  
+    slot_no, 
+    txn_index,
+    catalyst_id
+FROM 
+    catalyst_id_for_stake_hash
+WHERE 
+    stake_hash = :stake_hash
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/queries/cql/get_catalyst_id_for_stake_hash.cql:8]:
```suggestion
    stake_address = :stake_address
```

File: catalyst-gateway/bin/src/db/index/queries/cql/get_stake_addr_w_stake_hash.cql [hunk 16]
```diff
@@ -0,0 +1,3 @@
+SELECT stake_public_key
+FROM   stake_registration
+WHERE  stake_hash = :stake_hash;
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/queries/cql/get_stake_addr_w_stake_hash.cql:3]:
```suggestion
WHERE  stake_addrerss = :stake_address;
```

File: catalyst-gateway/bin/src/db/index/queries/cql/get_txo_by_stake_address.cql [hunk 17]
```diff
@@ -1,10 +1,10 @@
...
-    txn,
+    txn_id,
+    txn_index,
     txo,
     slot_no,
     value,
     spent_slot
 FROM txo_by_stake
-WHERE stake_address = :stake_address
+WHERE stake_hash = :stake_hash
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/queries/cql/get_txo_by_stake_address.cql:9]:
```suggestion
WHERE stake_address = :stake_address
```

File: catalyst-gateway/bin/src/db/index/queries/cql/update_txo_spent.cql [hunk 18]
```diff
@@ -1,7 +1,7 @@
 -- Update TXO Spent by the stake address
 UPDATE txo_by_stake
     SET spent_slot = :spent_slot
-WHERE stake_address = :stake_address
-    AND txn = :txn
+WHERE stake_hash = :stake_hash
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/queries/cql/update_txo_spent.cql:4]:
```suggestion
WHERE stake_address = :stake_address
```

File: catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_catalyst_id_for_stake_hash.cql [hunk 19]
```diff
@@ -0,0 +1,5 @@
+-- Delete Catalyst ID For Stake Address (RBAC 509 registrations).
+DELETE FROM catalyst_id_for_stake_hash
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_catalyst_id_for_stake_hash.cql:2]:
```suggestion
DELETE FROM catalyst_id_for_stake_address
```

File: catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_rbac_registration.cql [hunk 20]
```diff
@@ -0,0 +1,6 @@
+-- Delete RBAC 509 registration.
+DELETE FROM rbac_registration
+WHERE catalyst_id = :catalyst_id
+    AND txn_id = :txn_id
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_rbac_registration.cql:4]: not a key field
```suggestion
```

**Review by stevenj — COMMENTED** [review]
I added a bunch of comments although most of the issues are the same/related.
First start with a global search and replace of `stake_hash` back to `stake_address` and fix any fallout that occurs.  
There is a tx_id in a table/s that will mess up cassandras clustering, needs to be removed.  And there is a table I can't work out a use for, getting catalyst id by a transactions id??  A bunch of other miscellaneous things as well.
I may have missed a bunch of fallout but if i amek a comment that can apply elsewhere or i missed a side effect of a comment i made, then its implied they are corrected as well.
It looks a lot, but these are not huge issues.

File: catalyst-gateway/bin/Cargo.toml [hunk 21]
```diff
@@ -4,26 +4,26 @@ description = "The Catalyst Data Gateway"
...
-catalyst-signed-doc = { version = "0.0.1", git = "https://github.com/input-output-hk/catalyst-libs.git", tag = "r20250204-00" }
-catalyst-types = { version = "0.0.1", git = "https://github.com/input-output-hk/catalyst-libs.git", tag = "r20250128-01" }
+# TODO: FIXME: Use tag!
+cardano-chain-follower = { version = "0.0.6", git = "https://github.com/input-output-hk/catalyst-libs.git", branch = "version-hack" }
+rbac-registration = { version = "0.0.2", git = "https://github.com/input-output-hk/catalyst-libs.git", branch = "version-hack" }
+catalyst-types = { version = "0.0.1", git = "https://github.com/input-output-hk/catalyst-libs.git", branch = "version-hack" }
+cardano-blockchain-types = { version = "0.0.1", git = "https://github.com/input-output-hk/catalyst-libs.git", branch = "version-hack" }
+catalyst-signed-doc = { version = "0.0.1", git = "https://github.com/input-output-hk/catalyst-libs.git", branch = "version-hack" }
 
 pallas = { version = "0.30.1", git = "https://github.com/input-output-hk/catalyst-pallas.git", rev = "9b5183c8b90b90fe2cc319d986e933e9518957b3" }
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/Cargo.toml:24]: I have created an issue: https://github.com/input-output-hk/catalyst-voices/issues/1862

File: catalyst-gateway/bin/src/db/index/schema/mod.rs [hunk 22]
```diff
@@ -14,76 +14,77 @@ use crate::{settings::cassandra_db, utils::blake2b_hash::generate_uuid_string_fr
 const CREATE_NAMESPACE_CQL: &str = include_str!("./cql/namespace.cql");
 
 /// All Schema Creation Statements
+// This list is sorted alphabetically in the same order as the corresponding files.
```
[the remark this answers is not in the document]
Comment (stevenj) [reply catalyst-gateway/bin/src/db/index/schema/mod.rs:17]: If anything, this comment should just be "add new tables at the bottom, if a schema name is changed replace it in the same location".  So that diffs are minimized to real changes.  That should be easier to maintain.

File: catalyst-gateway/bin/src/cardano/mod.rs [hunk 23]
```diff
@@ -403,11 +405,11 @@ impl SyncTask {
                     // or there is an error.  If this is not a roll forward, log an error.
                     // It can fail if the index DB goes down in some way.
                     // Restart it always.
-                    if finished.end == TIP_POINT {
+                    if finished.end == Point::TIP {
                         if let Some(ref roll_forward_point) = finished.follower_roll_forward {
                             // Advance the known immutable tip, and try and start followers to reach
                             // it.
-                            self.immutable_tip_slot = roll_forward_point.slot_or_default();
+                            self.immutable_tip_slot = roll_forward_point.slot_or_default().into();
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/cardano/mod.rs:412]: Initially I decided to keep `u64` in `SyncTask`. Fixed.

File: catalyst-gateway/bin/src/db/index/block/rbac509/cql/insert_catalyst_id_for_txn_id.cql [hunk 24]
```diff
@@ -0,0 +1,12 @@
+-- Index of Catalyst ID For TX ID. RBAC 509 registrations.
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/block/rbac509/cql/insert_catalyst_id_for_txn_id.cql:1]: During indexing we using this table to find a Catalyst ID with the previous transaction id/hash.

File: catalyst-gateway/bin/src/db/index/schema/cql/stake_registration.cql [hunk 25]
```diff
@@ -2,19 +2,19 @@
 -- Can also be used to convert a known stake key hash back to a full stake address.
 CREATE TABLE IF NOT EXISTS stake_registration (
     -- Primary Key Data
-    stake_hash      blob,     -- 28 Bytes Stake Key Hash.
-    slot_no         varint,   -- slot number when the key_was_registered/re-registered.
-    txn             smallint, -- Index of the TX which holds the registration data.
+    stake_hash       blob,     -- 29 Byte stake hash (CIP19), zero length if not staked.
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/schema/cql/stake_registration.cql:5]: This logic was here before, according to the comments, but I will update it.

File: catalyst-gateway/bin/src/db/index/schema/mod.rs (hunk 22 above)
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/schema/mod.rs:17]: I will revert the changes, but when checking if all the tables are present in this list it was easier for me to have them in the same order as in the `schema/cql` folder.

File: catalyst-gateway/bin/src/db/index/tests/mod.rs [hunk 26]
```diff
@@ -15,7 +17,7 @@ static SHARED_SESSION: OnceCell<Result<(), String>> = OnceCell::const_new();
 
 /// Use this message to prevent a long message from getting a session.
 /// There is already a function that handling the error with its full form.
-const SESSION_ERR_MSG: &str = "Failed to initialize or get a database session.";
+pub const SESSION_ERR_MSG: &str = "Failed to initialize or get a database session.";
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/tests/mod.rs:20]: I don't mind adding `pub(crate)`, but the whole `tests` module is private and is hidden under the `cfg(test)` feature, so it isn't accessible outside.

[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/tests/mod.rs:20]: I guess I do mind a little bit. 🙃 I think that adding `pub(crate)` by default is just adds unnecessary clutter and exposes things that shouldn't be exposed even though it is only related to other modules and not to the outside world. Anyway, I have added `pub(crate) here.

File: catalyst-gateway/bin/src/service/api/cardano/mod.rs [hunk 27]
```diff
@@ -1,17 +1,18 @@
 //! Cardano API endpoints
+
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/service/api/cardano/mod.rs:2]: I have commented the `rbac_role0_key_chain_root` endpoint because it generated some errors. So I either need to fix it or comment the code, but I will check it again.

File: catalyst-gateway/bin/src/service/common/auth/rbac/mod.rs [hunk 28]
```diff
@@ -1,5 +1,7 @@
 //! Catalyst RBAC Authorization
 
+/// Catalyst RBAC Token Role 0 Kid
+pub(crate) mod role0_kid;
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/service/common/auth/rbac/mod.rs:4]: It wasn't added by me, but I will happily remove it. 🙃

File: catalyst-gateway/bin/src/metrics/chain_follower/mod.rs [hunk 29]
```diff
@@ -187,10 +188,10 @@ fn report_live(
         .set(i64::try_from(stats.blocks).unwrap_or(-1));
     reporter::LIVE_HEAD_SLOT[net_idx]
         .with_label_values(&[api_host_names, service_id, &network])
-        .set(i64::try_from(stats.head_slot).unwrap_or(-1));
+        .set(i64::try_from(u64::from(stats.head_slot)).unwrap_or(-1));
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/metrics/chain_follower/mod.rs:191]: Currently we only define the conversion from `Slot` to `u64` and it is infallible, but as far as I can see, the `prometheus` library requires `i64`.

File: catalyst-gateway/bin/src/db/index/schema/cql/rbac_registration.cql [hunk 30]
```diff
@@ -0,0 +1,15 @@
...
+    -- Primary Key Data
+    catalyst_id         text,           -- Short Catalyst id
+    slot_no             varint,         -- slot number of the txn_id. (u64)
+    txn_index           smallint,       -- Index of the TX which holds the registration data. (i16)
+
+    -- Non-Key Data
+    txn_id              blob,           -- 32 Bytes of Transaction Hash. (TransactionHash)
+    prv_txn_id          blob,           -- 32 Bytes from Previous Transaction Hash.
+    purpose             uuid,           -- 16 Bytes of UUIDv4 Purpose.
+
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/schema/cql/rbac_registration.cql:12]:
```suggestion
    stake_address       blob,       -- 29 Byte stake hash (CIP19) [only set when the registration has a stake address attached]

```

File: catalyst-gateway/bin/src/db/index/schema/cql/rbac_registration.cql [hunk 31]
```diff
@@ -0,0 +1,15 @@
...
+    PRIMARY KEY (catalyst_id, slot_no, txn_index)
+)
+WITH CLUSTERING ORDER BY (slot_no DESC, txn_index DESC);
```
Comment (stevenj) [inline catalyst-gateway/bin/src/db/index/schema/cql/rbac_registration.cql:15]:
```suggestion
WITH CLUSTERING ORDER BY (slot_no DESC, txn_index DESC);

CREATE INDEX cat_id_by_transaction_id ON rbac_registration (txn_id);
CREATE INDEX cat_id_by_stake_address ON rbac_registration(stake_address);
```

**Review by stevenj — COMMENTED** [review]
Lets try adding secondary indexes for stake_address and catalyst_id to this table.
If that works, we can remove the `catalyst_id_for_...` tables as they are being used as indexes.
We should then be able to query on these two fields as keys.
See: https://opensource.docs.scylladb.com/stable/features/secondary-indexes.html

File: catalyst-gateway/bin/src/db/index/block/certs.rs [hunk 32]
```diff
@@ -153,114 +158,110 @@ impl CertInsertQuery {
...
+                stake_hash
             );
         }
 
-        if pubkey.is_empty() && !script && delegation.is_some() {
+        if pubkey.is_none() && !script && delegation.is_some() {
             error!(
                 "Stake Delegation Certificate {:?} is NOT Witnessed.",
-                key_hash
+                stake_hash
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/block/certs.rs]: Not it is. 🙃 

https://github.com/input-output-hk/catalyst-libs/pull/217

File: catalyst-gateway/bin/src/service/common/types/cardano/hash29.rs [hunk 33]
```diff
@@ -0,0 +1,96 @@
+//! Hex encoded 29 byte hash.
+//!
+//! Hex encoded string which represents a 29 byte hash.
+
+use std::{
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/service/common/types/cardano/hash29.rs]: Removed.

File: catalyst-gateway/bin/src/db/index/block/rbac509/cql/insert_catalyst_id_for_txn_id.cql (hunk 24 above)
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/block/rbac509/cql/insert_catalyst_id_for_txn_id.cql:1]: Discussed: the table stays for now, but we try to replace it with a secondary index.

File: catalyst-gateway/bin/src/db/index/schema/cql/catalyst_id_for_txn_id.cql [hunk 34]
```diff
@@ -0,0 +1,12 @@
+-- Index of Chain Root For TX ID. RBAC 509 registrations.
```
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/schema/cql/catalyst_id_for_txn_id.cql]: Discussed: the table is current used to find a Catalyst ID for non-root registrations.

File: catalyst-gateway/bin/src/service/api/cardano/mod.rs (hunk 27 above)
[the remark this answers is not in the document]
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/service/api/cardano/mod.rs:2]: I have reverted changes and restored the endpoint.

File: catalyst-gateway/bin/src/service/common/types/cardano/catalyst_id.rs [hunk 35]
```diff
@@ -0,0 +1,106 @@
...
+
+/// A schema.
+static SCHEMA: LazyLock<MetaSchema> = LazyLock::new(|| {
+    MetaSchema {
+        title: Some("Catalyst short ID".into()),
+        description: Some("Catalyst short identifier in string format"),
+        example: Some("cardano/FftxFnOrj2qmTuB2oZG2v0YEWJfKvQ9Gg8AgNAhDsKE".into()),
+        ..MetaSchema::ANY
+    }
+});
```
Comment (apskhem) [inline catalyst-gateway/bin/src/service/common/types/cardano/catalyst_id.rs:23]: Consider adding the `pattern` field to this.

File: catalyst-gateway/bin/src/service/common/types/cardano/catalyst_id.rs [hunk 36]
```diff
@@ -0,0 +1,106 @@
...
+    types::{Example, ParseError, ParseFromJSON, ParseFromParameter, ParseResult, ToJSON, Type},
+};
+use serde_json::Value;
+
+/// A schema.
+static SCHEMA: LazyLock<MetaSchema> = LazyLock::new(|| {
+    MetaSchema {
+        title: Some("Catalyst short ID".into()),
+        description: Some("Catalyst short identifier in string format"),
+        example: Some("cardano/FftxFnOrj2qmTuB2oZG2v0YEWJfKvQ9Gg8AgNAhDsKE".into()),
```
Comment (apskhem) [inline catalyst-gateway/bin/src/service/common/types/cardano/catalyst_id.rs:20]: Why don't use the example from the implemented `Example` one (but convert it to string first)? This will make it sync to each other.

File: catalyst-gateway/bin/src/db/index/tests/mod.rs [hunk 37]
```diff
@@ -15,7 +17,7 @@ static SHARED_SESSION: OnceCell<Result<(), String>> = OnceCell::const_new();
 
 /// Use this message to prevent a long message from getting a session.
 /// There is already a function that handling the error with its full form.
-const SESSION_ERR_MSG: &str = "Failed to initialize or get a database session.";
+pub(crate) const SESSION_ERR_MSG: &str = "Failed to initialize or get a database session.";
```
Comment (apskhem) [inline catalyst-gateway/bin/src/db/index/tests/mod.rs:20]: Why did you change this to `pub(crate)`? It supposed to use only within this test module. Or do you need to make use outside of this?

File: catalyst-gateway/bin/src/db/index/tests/mod.rs [hunk 38]
```diff
@@ -42,7 +44,8 @@ fn get_session() -> Result<(Arc<CassandraSession>, Arc<CassandraSession>), Strin
     Ok((persistent, volatile))
 }
 
-async fn get_shared_session() -> Result<(Arc<CassandraSession>, Arc<CassandraSession>), String> {
+pub async fn get_shared_session() -> Result<(Arc<CassandraSession>, Arc<CassandraSession>), String>
```
Comment (apskhem) [inline catalyst-gateway/bin/src/db/index/tests/mod.rs:47]: Also same with this function. Why did you make it as `pub`? If it's not being use outside of this module.

File: catalyst-gateway/tests/Earthfile [hunk 39]
```diff
@@ -77,4 +77,4 @@ test-scylla:
 
     RUN --mount=$EARTHLY_RUST_CARGO_HOME_CACHE --mount=$EARTHLY_RUST_TARGET_CACHE \
         ./scylla_entry.sh && \
-        cargo nextest run --release --run-ignored=only scylla_session scylla_queries scylla_purge --no-fail-fast
+        cargo nextest run --release --run-ignored=only scylla_session scylla_queries scylla_purge rbac509 --no-fail-fast
```
Comment (apskhem) [inline catalyst-gateway/tests/Earthfile:80]: Maybe cosider to remove the added `rbac509`? As I couldn't see any test inside this module.

File: catalyst-gateway/bin/src/service/common/types/cardano/catalyst_id.rs (hunk 36 above)
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/service/common/types/cardano/catalyst_id.rs:20]: Great suggestions, thanks!

File: catalyst-gateway/bin/src/db/index/tests/mod.rs (hunk 37 above)
Comment (stanislav-tkach) [reply catalyst-gateway/bin/src/db/index/tests/mod.rs:20]: It was used in RBAC indexing tests (that require a database connection), but I will move these tests to `catalyst-gateway/bin/src/db/index/tests/` and make this private again.

File: catalyst-gateway/tests/Earthfile (hunk 39 above)
Comment (stanislav-tkach) [reply catalyst-gateway/tests/Earthfile:80]: There were tests in this [module](https://github.com/input-output-hk/catalyst-voices/blob/1ce134f3a10480a1bdcc6c6462cea634eb5f7a6c/catalyst-gateway/bin/src/db/index/block/rbac509/mod.rs#L260), but I will move them and update this like accordingly.

**Review by Mr-Leshiy — APPROVED** [review]
LGTM
