### PR TITLE
fix(cat-gateway): RBAC cache with RBAC auth token

### LINKED ISSUE #2433: Revise RBAC token validation
RBAC cache should be used to simplify a RBAC token validation.

### PR DESCRIPTION
**Pull request by bkioshn**
# Description

RBAC cache with RBAC auth token

## Related Issue(s)

Closes #2433

## Note

The integration test for auth token is expected to fail until RBAC cache is fully implemented

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

**Comment by stanislav-tkach** [comment]
There also this cache that can be removed:
```rust
static CACHE: LazyLock<Cache<EncodedAuthToken, CatalystRBACTokenV1>> = LazyLock::new(|| { ... }
```

File: catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs [hunk 1]
```diff
@@ -153,23 +151,18 @@ async fn checker_api_catalyst_auth(
...
-        },
-        Err(err) => {
-            debug!("Unable to build a registration chain Catalyst ID: {err:?}");
-            return Err(AuthTokenError::BuildRegChain(err.to_string()).into());
-        },
+    // Step 6: get the registration chain
+    // Get the registration from the persistent first, if not found, try volatile.
+    let reg_chain = RBAC_CACHE
+        .get(token.catalyst_id(), true)
+        .or_else(|| RBAC_CACHE.get(token.catalyst_id(), false));
```
Comment (stanislav-tkach) [inline catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs:158]: I'm not sure about that. As far as I understand, it is allowed to use volatile registrations everywhere. In that case I suppose we should be looking at volatile registrations first.

@stevenj @Mr-Leshiy

Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs:140]: Yes you are correct, we should always look at the volatile first.

**Review by Mr-Leshiy — CHANGES_REQUESTED** [review]

**Review by Mr-Leshiy — APPROVED** [review]
LGTM

**Comment by bkioshn** [comment]
If this is okay, I will merge it @stanislav-tkach
