### PR TITLE
fix: openapi specification

### LINKED ISSUE #143: 🛠️ [TASK] : Add OpenAPI linting to our CI process.
### Summary

Add OpenAPI linting for catalyst-gateway but in a way we can easily re-use on other targets.

### Description

We want to add openapi-linting to catalyst-gateway.
Catalyst-gateway auto generates the OpenAPI spec document,  but we still need to ensure it follows best practice.
This will help keep our documentation of high quality and ensure we don't have any issues that could cause problems for people trying to use our specifications or documentation.

We should use: https://github.com/stoplightio/spectral
It has a feature to allow it to lint any json/yaml document with custom rules.  As we want to use jason-schema to define forms for catalyst-gateway this could be a useful re-usable too to enforce consistency or limit our forms to features we support vs the entire json-schema feature set.

## Tasks

- [x] make a builder (or add to one) in cat-ci that incorporates `spectral` and any rulesets we want (both third party and in-house).
  - [x] Minimum 3rd party rule sets `owasp top 10` and `documentation` others listed in the spectral repo should be evaluated for usefulness given our projects.  This might be simply a target that exports the necessary ruleset artefacts, so they can be used consistently in other parts of the build.
  - [x] It might be easiest to just use the binary install method: https://meta.stoplight.io/docs/spectral/b8391e051b7d8-installation and integrate directly into the rust builder as our api's are generated from rust.
- [x] Generate the OpenAPI spec during the `build` step of catalyst-gateway, after the binary images themselves have been built.
- [x] Then add a check to run the linter against them with the necessary rules.  (If possible this could be a UDC to reduce boiler plate).
- [ ] Correct any issues the linter picks up in the `catalyst-gateway` API.
  - [ ] If the issue is with how Poem generates its specification we will need to work out how to make `poem` produce a compliant document, or temporarily disable the failing lint (or set it to a warning level) and then raise a ticket to fix `poem` upstream so it can produce better specifications.

### LINKED ISSUE #227: [Bug]: Undocumented [400] in cat-gateway open api definition
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 GET /api/registration/voter/{voting_key} 
 Undocumented HTTP status code
 Received: 400
 Documented: 200, 404, 500, 503

[400] Bad Request:
failed to parse parameter voting_key: verification failed. minLength(66)

To reproduce start cat-gateway on 127.0.0.1:3030 and run:
` curl -X GET 'http://127.0.0.1:3030/api/registration/voter/a6a3c0447aeb9cc54cf6422ba32b294e5e1c3ef6d782f2acff4a70694c4d1663?event_id=11'`

### Expected Behavior

_No response_

### Project

Backend

### What operating system are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Not Applicable

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bkioshn**
# Description

Correct any issues the linter picks up in the catalyst-gateway API.

## Related Issue(s)

Closes #143 Fix #227

## Related Pull Requests

#208 

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

File: catalyst-gateway/bin/src/service/api/registration/mod.rs [hunk 1]
```diff
@@ -54,19 +54,21 @@ impl RegistrationApi {
         &self, pool: Data<&Arc<State>>,
         /// A Voters Public ED25519 Key (as registered in their most recent valid
         /// [CIP-15](https://cips.cardano.org/cips/cip15) or [CIP-36](https://cips.cardano.org/cips/cip36) registration).
-        #[oai(validator(max_length = 66, min_length = 66, pattern = "0x[0-9a-f]{64}"))]
+        #[oai(validator(max_length = 64, min_length = 64, pattern = "[0-9a-f]{64}"))]
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/registration/mod.rs:57]: Is it needed to pass openapi linting ? Because it was added intentionally to have a following format `0x1b`

File: catalyst-gateway/bin/src/service/api/test_endpoints/mod.rs [hunk 2]
```diff
@@ -108,8 +108,8 @@ impl TestApi {
         /// The action just needs to be any valid UUID.
         ///
         /// # Make sure its a UUID
-        _action: Path<Option<String>>,
+        action: Path<String>,
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/test_endpoints/mod.rs:111]: Maybe it is good time just to remove these test endpoints ?
They have added as a reference how to work with the `poem-openapi` lib.
@stevenj

File: catalyst-gateway/bin/src/service/common/objects/voter_info.rs [hunk 3]
```diff
@@ -9,19 +9,22 @@ use super::{delegate_public_key::DelegatePublicKey, voter_group_id::VoterGroupId
 pub(crate) struct VoterInfo {
     /// Voter's voting power.
     /// This is the true voting power, subject to minimum voting power and max cap.
-    #[oai(validator(minimum(value = "0")))]
+    // TODO - Recheck max value
+    #[oai(validator(minimum(value = "0"), maximum(value = "1000000000000000000")))]
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/common/objects/voter_info.rs:13]: If I am not mistaken `"1000000000000000000"` stands as a `i64` maximum value right ?
Is so it makes sense to move it as a `const` value, somewhere in the `common` module

File: catalyst-gateway/bin/src/service/common/objects/voter_info.rs [hunk 4]
```diff
@@ -9,19 +9,22 @@ use super::{delegate_public_key::DelegatePublicKey, voter_group_id::VoterGroupId
...
     voting_power: i64,
 
     /// Voter's voting group.
     voting_group: VoterGroupId,
 
     /// Total voting power delegated to this voter.
     /// This is not capped and not subject to minimum voting power.
-    #[oai(validator(minimum(value = "0")))]
+    // TODO - Recheck max value
+    #[oai(validator(minimum(value = "0"), maximum(value = "1000000000000000000")))]
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/common/objects/voter_info.rs:22]: same

File: catalyst-gateway/bin/src/service/common/objects/voter_info.rs [hunk 5]
```diff
@@ -9,19 +9,22 @@ use super::{delegate_public_key::DelegatePublicKey, voter_group_id::VoterGroupId
...
     delegations_power: i64,
 
     /// Number of registration which delegated to this voter.
-    #[oai(validator(minimum(value = "0")))]
+    // TODO - Recheck max value
+    #[oai(validator(minimum(value = "0"), maximum(value = "1000")))]
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/common/objects/voter_info.rs:27]: as maximum boundary not quit clear at this moment, lets assigned it to the max `i64` value as you did previously.

**Review by Mr-Leshiy — CHANGES_REQUESTED** [review]

File: catalyst-gateway/bin/src/service/api/registration/mod.rs (hunk 1 above)
Comment (bkioshn) [reply catalyst-gateway/bin/src/service/api/registration/mod.rs:57]: The voting key example is 'a6a3c0447aeb9cc54cf6422ba32b294e5e1c3ef6d782f2acff4a70694c4d1663'

File: catalyst-gateway/bin/src/service/common/objects/voter_info.rs (hunk 3 above)
Comment (bkioshn) [reply catalyst-gateway/bin/src/service/common/objects/voter_info.rs:13]: Just a random number, but sure will do a max of `i64` apply to this. Don't think there is a max voting power right 🤔

File: catalyst-gateway/bin/src/service/common/objects/account_votes.rs [hunk 6]
```diff
@@ -35,6 +36,8 @@ pub(crate) struct AccountVote {
     /// The hex-encoded ID of the vote plan.
     pub(crate) vote_plan_id: VotePlanId,
     /// Array of the proposal numbers voted for by the account ID within the vote plan.
+    // TODO - Recheck max items and max value
```
Comment (FelipeRosa) [inline catalyst-gateway/bin/src/service/common/objects/account_votes.rs:39]: I'm a bit confused with this. Does this mean we need to verify that the values mentioned are correct? (i.e. you assigned the current values arbitrarily?)

**Review by FelipeRosa — COMMENTED** [review]
Left a comment, otherwise, LGTM

File: catalyst-gateway/bin/src/service/common/objects/account_votes.rs (hunk 6 above)
Comment (bkioshn) [reply catalyst-gateway/bin/src/service/common/objects/account_votes.rs:39]: Yes, if there is one.  Otherwise I will set to the maximum of the given type (eg. u8 will be set to u8::MAX)

File: catalyst-gateway/bin/src/service/common/objects/voter_info.rs (hunk 3 above)
Comment (Mr-Leshiy) [reply catalyst-gateway/bin/src/service/common/objects/voter_info.rs:13]: >Don't think there is a max voting power right 

Actually most probable that right now we already have some voting power limits, but don't remember what it is.

For now and for catalyst-gateway I think would be enough just put some reasonable maximum values as a limits for `i64` and "1000000000000000000" I think is ok, but it would be better to make as const with the appropriate name as `MAX_INTEGER` or something, to not to lose a context why we have such values.

Comment (bkioshn) [reply catalyst-gateway/bin/src/service/common/objects/voter_info.rs]: Somehow, variable can't be assigned to "value", so hard coded

File: catalyst-gateway/bin/src/service/api/test_endpoints/mod.rs (hunk 2 above)
Comment (bkioshn) [reply catalyst-gateway/bin/src/service/api/test_endpoints/mod.rs:111]: Steven told me about this, maybe will leave it there but just comment it out

**Review by Mr-Leshiy — DISMISSED** [review]
LGTM

File: catalyst-gateway/bin/src/service/common/objects/voter_info.rs [hunk 7]
```diff
@@ -9,30 +9,32 @@ use super::{delegate_public_key::DelegatePublicKey, voter_group_id::VoterGroupId
...
-    #[oai(validator(minimum(value = "0")))]
+    #[oai(validator(minimum(value = "0"), maximum(value = "9223372036854775807")))]
     delegations_count: i64,
 
     /// Voting power's share of the total voting power.
     /// Can be used to gauge potential voting power saturation.
     /// This value is NOT saturated however, and gives the raw share of total registered
     /// voting power.
-    #[oai(validator(minimum(value = "0"), maximum(value = "100")))]
+    #[oai(validator(minimum(value = "0"), maximum(value = "1.7976931348623157e308")))]
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/common/objects/voter_info.rs:31]: Should be 100

File: catalyst-gateway/bin/src/service/common/responses/resp_5xx.rs [hunk 8]
```diff
@@ -29,8 +29,12 @@ struct ServerErrorPayload {
     id: Uuid,
     /// *Optional* SHORT Error message.
     /// Will not contain sensitive information, internal details or backtraces.
+    // TODO - Recheck max length, pattern is added to avoid err from linter
+    #[oai(validator(max_length = "100", pattern = "^[0-9a-zA-Z]"))]
```
Comment (stevenj) [inline catalyst-gateway/bin/src/service/common/responses/resp_5xx.rs:33]: maybe add `.*$` to regex

**Review by stevenj — CHANGES_REQUESTED** [review]

File: catalyst-gateway/bin/src/service/common/responses/resp_5xx.rs (hunk 8 above)
Comment (stevenj) [reply catalyst-gateway/bin/src/service/common/responses/resp_5xx.rs:33]: Also don't forget to add your initials and a link to an issue for the TODO's.

**Review by stevenj — APPROVED** [review]
LGTM
