### PR TITLE
fix(cat-gateway): regex and parse param

### LINKED ISSUE #2461: 🛠️ [BUG] : Check Regex validation
### Summary

Check Regex validation

### Description

There is currently a mismatch between the Swagger regex validation and the internal validation.

###  Example

In this endpoint:

```rust
#[OpenApi(tag = "ApiTags::Cardano")]
impl Api {
    #[oai(
        path = "/v1/rbac/registration",
        method = "get",
        operation_id = "rbacRegistrations"
    )]
    async fn rbac_registrations_get(
        /// Stake address or Catalyst ID to get the RBAC registration for.
        Query(lookup): Query<Option<CatIdOrStake>>,
        /// No Authorization required, but Token permitted.
        auth: NoneOrRBAC,
    ) -> registrations_get::AllResponses {
        let token = auth.into();
        registrations_get::endpoint(lookup, token).await
    }
}
``` 

Assume that the type `CatIdOrStake` is annotated with a regex like `^(+\/[A-Za-z0-9_-]{43}|((stake_1)"`
This Regex only works in Swagger UI to prevent invalid input. However, this validation is not applied at runtime, meaning running `curl` can send invalid input that bypasses the regex  — leading to inconsistent behavior.

**Note** this `CatIdOrStake` is already fix in #2453

### PR DESCRIPTION
**Pull request by bkioshn**
# Description

The `PATTERN` specified in MetaSchema is only used by frontend tools like Swagger UI that extract the OpenAPI specification. However, this pattern validation is not enforced at runtime — for example, when making requests using `curl`. This leads to inconsistent behavior between documentation-based tools and actual API usage.

## Related Issue(s)

Closes #2461

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

**Review by stevenj — APPROVED** [review]
LGTM

File: catalyst-gateway/bin/src/service/common/types/cardano/asset_name.rs [hunk 1]
```diff
@@ -14,17 +14,21 @@ use crate::service::common::types::string_types::impl_string_types;
...
 /// Minimum length.
 const MIN_LENGTH: usize = 0;
-/// Maximum length. (True length is 32, but escaping can double its size).
-const MAX_LENGTH: usize = 64;
+/// Maximum length.
+const MAX_LENGTH: usize = 1000;
 /// Validation Regex Pattern
-const PATTERN: &str = r"[\S\s]{0,64}";
+/// Can be anything
+const PATTERN: &str = r".*";
```
Comment (apskhem) [inline catalyst-gateway/bin/src/service/common/types/cardano/asset_name.rs:31]: even though that it can be anything, we should still put the characters length limit.

File: catalyst-gateway/bin/src/service/common/types/generic/ed25519_public_key.rs [hunk 2]
```diff
@@ -145,14 +149,26 @@ impl TryInto<Vec<u8>> for Ed25519HexEncodedPublicKey {
 
 #[cfg(test)]
 mod tests {
-    use super::Ed25519HexEncodedPublicKey;
+    use super::*;
 
     #[test]
-    fn hex_to_pub_key() {
+    fn test_ed255519() {
```
Comment (apskhem) [inline catalyst-gateway/bin/src/service/common/types/generic/ed25519_public_key.rs:155]: `ed255519` or `ed25519`?

File: catalyst-gateway/bin/src/service/common/types/generic/uuidv4.rs [hunk 3]
```diff
@@ -23,7 +24,7 @@ const EXAMPLE: &str = "c9993e54-1ee1-41f7-ab99-3fdec865c744";
 pub(crate) const ENCODED_LENGTH: usize = EXAMPLE.len();
 /// Validation Regex Pattern
 pub(crate) const PATTERN: &str =
-    "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA0F]{3}-[0-9a-fA-F]{12}$";
+    "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$";
 /// Format
 pub(crate) const FORMAT: &str = "uuid";
```
Comment (apskhem) [inline catalyst-gateway/bin/src/service/common/types/generic/uuidv4.rs:29]: this can be more specific, `uuidv4`.

**Review by stanislav-tkach — APPROVED** [review]

File: catalyst-gateway/bin/src/service/common/types/cardano/cip19_shelley_address.rs [hunk 4]
```diff
@@ -142,3 +150,49 @@ impl Example for Cip19ShelleyAddress {
...
+            "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3n0d3vllmyqwsx5wktcd8cc3sq835lu7drv2xwl2wywfgs68faae",
+            "addr_test1zrphkx6acpnf78fuvxn0mkew3l0fd058hzquvz7w36x4gten0d3vllmyqwsx5wktcd8cc3sq835lu7drv2xwl2wywfgsxj90mg",
+            "addr_test1yz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzerkr0vd4msrxnuwnccdxlhdjar77j6lg0wypcc9uar5d2shsf5r8qx",
+            "addr_test1xrphkx6acpnf78fuvxn0mkew3l0fd058hzquvz7w36x4gt7r0vd4msrxnuwnccdxlhdjar77j6lg0wypcc9uar5d2shs4p04xh",
+            "addr_test1vz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzerspjrlsz",
+            "addr_test1wrphkx6acpnf78fuvxn0mkew3l0fd058hzquvz7w36x4gtcl6szpr",
+        ];
+
+        let invalid = [
+            "addr1gx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer5pnz75xxcrzqf96k",
```
Comment (cong-or) [inline catalyst-gateway/bin/src/service/common/types/cardano/cip19_shelley_address.rs:179]: what happens when you do deep nesting and repetition - wondering if it causes backtracking

for example "addr1gx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer5pnz75xxcrzqf96k@addr1gx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer5pnz75xxcrzqf96k.addr1gx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer5pnz75xxcrzqf96k.addr1gx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer5pnz75xxcrzqf96k"

Comment (cong-or) [reply catalyst-gateway/bin/src/service/common/types/cardano/cip19_shelley_address.rs:179]: sorry, this is just a wider comment for all our regex stuff.

Comment (bkioshn) [reply catalyst-gateway/bin/src/service/common/types/cardano/cip19_shelley_address.rs:179]: Thanks for pointing this out
It should be safe because the all regex here doesn't allow nested repetition and start and stop anchor us used,

**Review by cong-or — APPROVED** [review]
LGTM
