### PR TITLE
fix(cat-voices): some wallet icons don't render

### LINKED ISSUE #2196: [Bug]: Some wallet icons are not visible in the select cardano wallet page
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Some wallet icons are not visible in the select cardano wallet page (LACE, VESPR, YOROI, NUFI)

Image

### Expected Behavior

_No response_

### Project

Frontend

### What operating system are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```sh

```

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dt-iohk**
# Description

Displays svg wallet icons in a webview, flutter_svg is not capable of rendering them, they're too complex.

## Related Issue(s)

Closes #2196

## Screenshots

Screenshot 2025-04-23 at 08 42 59
Screenshot 2025-04-23 at 09 07 52

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

File: catalyst_voices/apps/voices/lib/widgets/images/voices_svg_image_webview.dart [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+      initialData: InAppWebViewInitialData(
+        data: _fullScreenSvgHtmlPage(widget.src),
+      ),
+      onReceivedError: (controller, request, error) {
+        if (mounted) {
+          setState(() {
+            _errorWidget = widget.errorBuilder(context, error, null);
+          });
+        }
+      },
```
Comment (damian-molinski) [inline catalyst_voices/apps/voices/lib/widgets/images/voices_svg_image_webview.dart:44]: change `_errorWidget` to `_error` na do mapping in `build`. Widgets should be build with current context

File: catalyst_voices/apps/voices/lib/widgets/menu/voices_wallet_tile.dart [hunk 2]
```diff
@@ -69,19 +73,38 @@ class VoicesWalletTileIcon extends StatelessWidget {
...
+      image = VoicesSvgImageWebview(
+        src: iconSrc,
+        errorBuilder: _errorBuilder,
+      );
+    } else {
+      image = Image.network(
+        iconSrc,
+        errorBuilder: _errorBuilder,
+      );
+    }
```
Comment (damian-molinski) [inline catalyst_voices/apps/voices/lib/widgets/menu/voices_wallet_tile.dart:90]: Can we convert to using switch? 

```dart
final image = switch (iconSrc) {
  null => const _IconPlaceholder(),
  String src when src.contains('image/svg') => VoicesSvgImageWebview(
      src: src,
      errorBuilder: _errorBuilder,
    ),
  _ => Image.network(
      src, // Use the non-null 'src' variable captured by the pattern
      errorBuilder: _errorBuilder,
    ),
};
```
