### PR TITLE
fix(cat-gateway): OpenAPI Lint Cleanup Part 2

### LINKED ISSUE #1029: 🛠️ [TASK] : Cleanup API endpoints
### Summary

Cleanup API endpoints

### Description

Cleanup the existing endpoint in `catalyst-gateway`

### Subtasks
- [x] Change the existing endpoints to `draft`
    - All API should be `/api/draft/*` except for `health` and existing versioned endpoint. 
    - `/api/v1/health` `v1` can be assign to `health` endpoint since it is stable
- [x]  Remove `BadRequest` from [ErrorResponse](https://github.com/input-output-hk/catalyst-voices/blob/a330c53efca17fb52c872e104e2da833c4102ea1/catalyst-gateway/bin/src/service/common/responses/mod.rs#L26)
    - Bad Request 400 should be custom to a certain endpoint
    - Check the existing endpoint that may return 400 and assign appropriate BadRequest error
- [x] config endpoint should get json schema from OpenAPI specification
- [x] Add openapi linting rule in `.spectral`
    - Checking the api path
    - Checking that the content type shouldn't be `text/plain`
    - All properties and schema should contains example
    - If content type is `application/json` it should be object
- [x] Revisit document
- [x] Restructure legacy endpoints
    - All legacy endpoints should be under Legacy tag
- [x] Add API key auth
- [x] Properly handle response (401, 403, 422, 429, 500, 503
- [x] Handle headers (retry after, ratelimit, access control allow origin

### PR DESCRIPTION
**Pull request by stevenj**
# Description

2nd iteration of API cleanup.

## Related Issue(s)

Part 2 of #1029

## Related Pull Requests

#1036

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

File: catalyst-gateway/bin/src/service/common/objects/cardano/cip36.rs [hunk 1]
```diff
@@ -60,12 +62,11 @@ impl Example for Cip36Reporting {
 }
 
 /// CIP36 Registration Data as found on-chain.
-#[derive(Object, Default)]
+#[derive(Object)]
 #[oai(example = true)]
 pub(crate) struct Cip36Info {
```
Comment (bkioshn) [inline catalyst-gateway/bin/src/service/common/objects/cardano/cip36.rs:67]: Is it possbile to change `payment_address` to `payment_key`

File: catalyst-gateway/bin/src/service/api/cardano/rbac/chain_root_get.rs [hunk 2]
```diff
@@ -40,12 +41,14 @@ pub(crate) type AllResponses = WithErrorResponses<Responses>;
 pub(crate) async fn endpoint(stake_address: Cip19StakeAddress) -> AllResponses {
     let Some(session) = CassandraSession::get(true) else {
         error!("Failed to acquire db session");
```
Comment (bkioshn) [inline catalyst-gateway/bin/src/service/api/cardano/rbac/chain_root_get.rs:43]: Do we need to log an error here? since it is already log in `service_unavailable`
for `internal_error` too

File: catalyst-gateway/bin/src/service/common/types/cardano/asset_name.rs [hunk 3]
```diff
@@ -0,0 +1,89 @@
+//! Hex encoded 28 byte hash.
```
Comment (bkioshn) [inline catalyst-gateway/bin/src/service/common/types/cardano/asset_name.rs:1]: Cardano Native Assets

File: catalyst-gateway/bin/src/service/common/types/generic/ed25519_public_key.rs [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+
+use poem_openapi::{
+    registry::{MetaSchema, MetaSchemaRef},
+    types::{Example, ParseError, ParseFromJSON, ParseFromParameter, ParseResult, ToJSON, Type},
+};
+use serde_json::Value;
+
+use crate::{service::common::types::string_types::impl_string_types, utils::ed25519};
+
+/// Stake address title.
```
Comment (bkioshn) [inline catalyst-gateway/bin/src/service/common/types/generic/ed25519_public_key.rs:19]: Change all "Stake address" to "Ed25519 Public Key"

File: catalyst-gateway/bin/src/service/api/cardano/rbac/chain_root_get.rs (hunk 2 above)
Comment (stevenj) [reply catalyst-gateway/bin/src/service/api/cardano/rbac/chain_root_get.rs:43]: How do we know where the error came from?

File: catalyst-gateway/bin/src/service/common/types/generic/ed25519_public_key.rs (hunk 4 above)
Comment (stevenj) [reply catalyst-gateway/bin/src/service/common/types/generic/ed25519_public_key.rs:19]: Fixed comments

File: catalyst-gateway/bin/src/service/common/objects/cardano/cip36.rs (hunk 1 above)
Comment (stevenj) [reply catalyst-gateway/bin/src/service/common/objects/cardano/cip36.rs:67]: I believe the comment is wrong, and payment address is literally the payment address.
It should be cip19 encoded if it is, not a hex value.
I am yet to fix this area up in the API's
Will be part of future PR's.

File: catalyst-gateway/bin/src/service/api/cardano/rbac/chain_root_get.rs (hunk 2 above)
Comment (stevenj) [reply catalyst-gateway/bin/src/service/api/cardano/rbac/chain_root_get.rs:43]: Its fine for now.
