### PR TITLE
fix(cat-gateway): implement a proper pagination for sign doc

### LINKED ISSUE #1690: Catalyst Signed Document POST endpoint. Proper `CurrentPage` response returning.
### Summary

Implement a proper `page` response filed setup https://github.com/input-output-hk/catalyst-voices/blob/0c6d28626efc4e4e6259136f1ade3110b27ef75c/catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs#L61.

### Description

Need to instantiate a proper `CurrentPage` structure object.
```
pub(crate) struct CurrentPage {
    #[allow(clippy::missing_docs_in_private_items)] // Type is pre documented
    pub page: common::types::generic::query::pagination::Page,
    #[allow(clippy::missing_docs_in_private_items)] // Type is pre documented
    pub limit: common::types::generic::query::pagination::Limit,
    #[allow(clippy::missing_docs_in_private_items)] // Type is pre documented
    pub remaining: common::types::generic::query::pagination::Remaining,
}
```
`page` and `limit` field could be defined from the endpoint request arguments.
`remaining` field should be calculated as a difference between the resulted number of elements returned by the query and the total amount of elements (applying the same filtering options).
It will be needed to add a new sql request as this https://github.com/input-output-hk/catalyst-voices/blob/f83a33f7c2a11607485ee6d19f33269e066187da/catalyst-gateway/bin/src/db/event/signed_docs/sql/filtered_select_signed_documents.sql.jinja, but it should SELECT just a count of rows.

### PR DESCRIPTION
**Pull request by bkioshn**
# Description

Implement a proper pagination for sign document

## Related Issue(s)
Closes #1690 

## Description of Changes
- Fix how offset is calculated from page and limit
- Create query for counting the total sign doc with filter
- Calculate the remaining where it is the number of items remaining to be returned after this page

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [ ] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

**Review by stanislav-tkach — APPROVED** [review]

File: catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs [hunk 1]
```diff
@@ -1,6 +1,6 @@
 //! Document Index Query
 
-use std::future;
+use std::future::{self};
```
Comment (Mr-Leshiy) [inline catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs:3]:
```suggestion
use std::future;
```

**Review by Mr-Leshiy — COMMENTED** [review]
despite

**Review by Mr-Leshiy — APPROVED** [review]
LGTM

**Review by Mr-Leshiy — APPROVED** [review]
LGTM
